language: python

sudo: false

env:
    - TOX_ENV=py27-django1.7
    - TOX_ENV=py27-django1.8
    - TOX_ENV=py27-django1.9
    - TOX_ENV=py27-django1.10
    - TOX_ENV=py34-django1.7
    - TOX_ENV=py34-django1.8
    - TOX_ENV=py34-django1.9
    - TOX_ENV=py34-django1.10

install:
  - pip install tox coverage coveralls

script:
  - coverage erase
  - tox -e $TOX_ENV

after_success:
  - coverage combine
  - coveralls
